image:
- Visual Studio 2017
- Ubuntu1804

branches:
  except:
    - l10n_master
    - gh-pages

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true

services:
- docker

stack: node 10

init:
- ps: Install-Product node 10

install:
- ps: choco install cloc --no-progress
- ps: cloc --include-lang TypeScript,JavaScript,HTML,Sass,CSS --vcs git
- ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version

before_build:
- node --version
- npm --version
- cmd: set "GIT_PATH=C:\Program Files\Git\mingw64\libexec\git-core"
- cmd: set "PATH=%GIT_PATH%;%PATH%"

build_script:
- sh: chmod +x ./build-ci.sh
- sh: ./build-ci.sh
- cmd: npm install
- cmd: npm run build:prod

after_build:
- sh: docker logout
